name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Blah
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/dowload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Ouput info
        run: echo "Deploying & uploading..."